const enum Message {
  
  // Access Control Errors
  ACCESS_FORBIDDEN = "ACCESS_FORBIDDEN",
  ACCESS_UNAUTHORIZED = "ACCESS_UNAUTHORIZED",
  TOO_MANY_REQUESTS="TOO_MANY_REQUESTS",

  USER_CREATION_FAILED = "Failed to create user",

  EMAIL_ALREADY_EXISTS="Email already exits",
  INVALID_CREDENTIALS = "Invalid credentials",
  EMAIL_NOT_VERIFIED = "Email not verified",
  // Validation and Resource Errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  BAD_REQUEST = "BAD REQUEST",
  RESOURCES_ALREADY_EXITS = "RESOURCES_ALREADY_EXITS",

  // System Errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  VERIFICATION_ERROR = "VERIFICATION_ERROR",
}

export { Message };